### ISSUE TITLE
Build fails on Windows machines

### ISSUE THREAD

**Issue by undnull** [voxelius/voxelius#1]
#### Description
Building fails on any Windows machine due to `<filesystem>` being freaky and VC++ lacking hashing functionality for `std::filesystem::path`.

#### Steps to reproduce
1. Clone the repo
2. Setup CMake environment
3. Build the project
4. Observe compiler errors

#### Expected behaviour
The project builds as intended

#### Miscellaneous
* For paths, a hack with ifdef(WIN32)-ing should cover everything.
* For path hashing, a dumb path2string hasher is enough as Voxelius doesn't internally use native and not normalized paths.

**Comment by PQCraft** [comment]
Try using MinGW instead

**Comment by PQCraft** [comment]
@undnull You can't cast it?

**Comment by undnull** [comment]
> @undnull You can't cast it?

...No?  
Casting `std::wstring` to `std::string` without `wcstombs` is a _bad idea_

**Comment by PQCraft** [comment]
Average C++ moment

**Comment by undnull** [comment]
> Average C++ moment

It's not related to the language but rather to Windows being an asshole

**Comment by PQCraft** [comment]
For me in C, Windows uses `char*` for everything and there are functions appended with `W` if you want to use wchar.

**Comment by PQCraft** [comment]
It encodes the utf-8 directly (i forgot how to do it, but it does some strange bit slicing that actually works (CLIBASIC can do it))

**Comment by undnull** [comment]
> For me in C, Windows uses `char*` for everything and there are functions appended with `W` if you want to use wchar.

It depends on build settings but natively Windows does things with wide characters, hence `path.native()` returns `wstring`

**Comment by PQCraft** [comment]
I found this:
https://stackoverflow.com/questions/45401822/how-to-convert-filesystem-path-to-string

**Comment by undnull** [comment]
> I found this: https://stackoverflow.com/questions/45401822/how-to-convert-filesystem-path-to-string

It may work but I want to have native path separators as PhysFS requires non-virtual paths to have those

**Comment by undnull** [comment]
No wait...

`u8string()`
returns the path in native pathname format converted to a string

**Comment by PQCraft** [comment]
@undnull 
> It may work but I want to have native path separators as PhysFS requires non-virtual paths to have those
I would just make a `platformPath` function that took a string and returned a string. On Windows, it would replace every `/` with `\` in the string and on everything else, it would do nothing.

**Comment by undnull** [comment]
Will be fixed in #3
