### ISSUE TITLE
ImGui crash involving fonts

### ISSUE THREAD

**Issue by PQCraft** [voxelius/voxelius#17]
### Description
The game crashes when changing the font via ImGui's internal style editor and then resizing the window.  

### Steps to reproduce
1. Launch `vgame`  
2. Get ImGui style editor to show (currently in `Play Game/Worlds`)  
3. Select a different default font
4. Resize the window causing a font reload
5. Observe everything blowing up

### Expected behavior
The game that _doesn't implode_

### Miscellaneous
From Discord:
```
vgame: imgui/src/imgui.cpp:7254: void ImGui::SetCurrentFont(ImFont*): Assertion `font && font->IsLoaded()' failed
```

**Comment by untodesu** [comment]
![изображение](https://github.com/user-attachments/assets/d16569e6-5ed0-4ee8-bd11-5967bece1a02)
