### ISSUE TITLE
Add a crosshair

### ISSUE THREAD

**Issue by TheGreatJaeger** [voxelius/voxelius#31]
### Description
A crosshair because it's hard to see where's the screen center (thus you can't see where you place voxels)  

### Possible solution
Literally add a crosshair

### Miscellaneous
Literally add a crosshair

I can't see where I'm placing blocks :/

**Comment by untodesu** [comment]
f65f72e0706ee22d2278257c7e8171d3ce88c00a added a minecraft-esque cursor

![Image](https://github.com/user-attachments/assets/fefdc272-e614-4ba6-8a59-e4f0834cffbc)
